### PR TITLE
Update Dockerfile-1.9 and create Dockerfile-1.10

### PR DESCRIPTION
**Pull request by orthomind**
I've copied the Dockerfile-1.9 and Dockerfile-1.10 files from the decred/dcrd repository.  As best I can tell, it appears some of the 'decred-golang-builder' images are build from decred/dcrdocker, while more recent ones are from decred/dcrd (if that's not correct, please let me know).

These images appear to be distinct from dcrd, and used across repos, so I think it makes sense to have them in decred/dcrdocker.  My proposal:

1.  Merge this PR
2.  Update docker hub build process to use images from this repo only (decred-golang-builder-1.9 and decred-golang-builder-1.10 specifically)
3.  I'll create a PR to remove these Dockerfiles from decred/dcrd once they're not being used

### CODE REVIEW

**Comment by dajohi** [comment]
Please rebase against master.  Also, remove Dockerfile-1.8 since you are adding 1.10.

**Comment by saward** [comment]
@dajohi Done

**Comment by orthomind** [comment]
@dajohi Done

**Comment by dajohi** [comment]
Also, please force the specific current latest version for both 1.9 and 1.10.

**Comment by orthomind** [comment]
Also done.

**Pull request closed without merging**
